name: Entity Intelligence Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    - name: Intalling .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100-preview.7.23376.3
        include-prerelease: true
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
