name: Entity Intelligence Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checking Out Code
      uses: actions/checkout@v3
    - name: Installing .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100-preview.7.23376.3
    - name: Restoring NuGet Packages
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
